// Language icons for visual identification
export const LANGUAGE_ICONS: Record<string, { abbrev: string; color: string }> = {
  // Popular languages
  javascript: { abbrev: "JS", color: "#f7df1e" },
  typescript: { abbrev: "TS", color: "#3178c6" },
  python: { abbrev: "PY", color: "#3776ab" },
  rust: { abbrev: "RS", color: "#dea584" },
  go: { abbrev: "GO", color: "#00add8" },
  java: { abbrev: "JV", color: "#ed8b00" },
  kotlin: { abbrev: "KT", color: "#7f52ff" },
  swift: { abbrev: "SW", color: "#fa7343" },
  c: { abbrev: "C", color: "#a8b9cc" },
  "c++": { abbrev: "C+", color: "#00599c" },
  "c#": { abbrev: "C#", color: "#512bd4" },
  ruby: { abbrev: "RB", color: "#cc342d" },
  php: { abbrev: "PH", color: "#777bb4" },
  html: { abbrev: "HT", color: "#e34f26" },
  css: { abbrev: "CS", color: "#1572b6" },
  sql: { abbrev: "SQ", color: "#e38c00" },
  bash: { abbrev: "SH", color: "#4eaa25" },
  shell: { abbrev: "SH", color: "#4eaa25" },
  powershell: { abbrev: "PS", color: "#012456" },
  dockerfile: { abbrev: "DK", color: "#2496ed" },
  yaml: { abbrev: "YM", color: "#cb171e" },
  json: { abbrev: "JS", color: "#292929" },
  markdown: { abbrev: "MD", color: "#083fa1" },
  graphql: { abbrev: "GQ", color: "#e10098" },
  lua: { abbrev: "LU", color: "#000080" },
  r: { abbrev: "R", color: "#276dc3" },
  scala: { abbrev: "SC", color: "#dc322f" },
  haskell: { abbrev: "HS", color: "#5e5086" },
  elixir: { abbrev: "EX", color: "#6e4a7e" },
  erlang: { abbrev: "ER", color: "#b83998" },
  dart: { abbrev: "DT", color: "#0175c2" },
  objectivec: { abbrev: "OC", color: "#438efb" },
  // More languages
  perl: { abbrev: "PL", color: "#39457e" },
  clojure: { abbrev: "CL", color: "#5881d8" },
  fsharp: { abbrev: "FS", color: "#b845fc" },
  groovy: { abbrev: "GV", color: "#4294b6" },
  gradle: { abbrev: "GD", color: "#02303a" },
  makefile: { abbrev: "MK", color: "#427819" },
  vim: { abbrev: "VI", color: "#199f73" },
  toml: { abbrev: "TM", color: "#9c4121" },
  xml: { abbrev: "XML", color: "#0060ac" },
};

// File extension to language name mapping
export const FILE_EXT_TO_LANG: Record<string, string> = {
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  ts: "typescript",
  tsx: "typescript",
  py: "python",
  pyw: "python",
  rs: "rust",
  go: "go",
  java: "java",
  kt: "kotlin",
  swift: "swift",
  c: "c",
  h: "c",
  cpp: "c++",
  cc: "c++",
  cxx: "c++",
  hpp: "c++",
  cs: "c#",
  rb: "ruby",
  php: "php",
  html: "html",
  htm: "html",
  css: "css",
  scss: "css",
  sql: "sql",
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  fish: "bash",
  ps1: "powershell",
  psd1: "powershell",
  dockerfile: "dockerfile",
  yaml: "yaml",
  yml: "yaml",
  json: "json",
  md: "markdown",
  mdx: "markdown",
  graphql: "graphql",
  gql: "graphql",
  lua: "lua",
  r: "r",
  R: "r",
  scala: "scala",
  hs: "haskell",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  dart: "dart",
  m: "objectivec",
  mm: "objectivec",
  pl: "perl",
  clj: "clojure",
  fs: "fsharp",
  fsx: "fsharp",
  groovy: "groovy",
  gradle: "gradle",
  makefile: "makefile",
  vim: "vim",
  toml: "toml",
  xml: "xml",
};

export function getLanguageInfo(fileName: string): { lang: string; abbrev: string; color: string } | null {
  const ext = fileName.split(".").pop()?.toLowerCase();
  if (!ext) return null;

  const langName = FILE_EXT_TO_LANG[ext];
  if (!langName) return null;

  const icon = LANGUAGE_ICONS[langName];
  if (!icon) return null;

  return { lang: langName, abbrev: icon.abbrev, color: icon.color };
}